server {
    # 监听 80 端口
    listen       80;
    server_name  localhost;

    # 根目录和默认页面
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 解决 history 路由模式下刷新 404 的问题
        try_files $uri $uri/ /index.html;
    }

    # 配置反向代理，将 /api 的请求转发给后端服务
    # 这里的 'ruoyi-backend' 是我们将在 docker-compose.yml 中定义的后端服务名
    location /api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://ruoyi-backend:8080/;
    }

    # 错误页面
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}